#!/usr/bin/env python3
import json
import time
import webbrowser
from pathlib import Path
from playwright.sync_api import sync_playwright

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_manual"

def main():
    print("Opening Instagram... please log in and complete 2FA.")
    print("The script will check every 5 seconds if you're logged in.")
    print("Once logged in, cookies will be saved automatically.")
    print()
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(viewport={"width": 1280, "height": 800})
        page = context.new_page()
        
        page.goto("https://www.instagram.com/accounts/login/")
        
        max_wait = 300  # 5 minutes max
        start_time = time.time()
        logged_in = False
        
        while time.time() - start_time < max_wait:
            time.sleep(5)
            
            # Check if logged in
            try:
                page.wait_for_selector("svg[aria-label='Home']", timeout=2000)
                logged_in = True
                break
            except:
                pass
            
            # Also check URL
            if "instagram.com" in page.url and "login" not in page.url.lower():
                logged_in = True
                break
                
            print(f"  Waiting for login... ({int(time.time() - start_time)}s)")
        
        if not logged_in:
            print("Timeout! Please log in faster next time.")
            browser.close()
            return
            
        print("Logged in! Saving cookies...")
        
        cookies = context.cookies()
        ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
        
        if len(ig_cookies) < 3:
            print(f"Error: Only {len(ig_cookies)} cookies found")
            browser.close()
            return
        
        # Save cookies.txt
        lines = ["# Netscape HTTP Cookie File", "# Generated by auto_login.py"]
        for c in ig_cookies:
            domain = c["domain"]
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", True) else "FALSE"
            expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
        
        COOKIE_FILE.write_text("\n".join(lines))
        print(f"Saved cookies to {COOKIE_FILE.name}")
        
        # Save session data
        session_data = {
            "cookies": ig_cookies,
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        }
        SESSION_FILE.write_text(json.dumps(session_data, indent=2))
        print(f"Saved session to {SESSION_FILE.name}")
        
        print("Done! You can close the browser now.")
        browser.close()

if __name__ == "__main__":
    main()