#!/usr/bin/env python3
"""
Auto Instagram Session Fixer — opens browser, waits for login, extracts cookies.
No interactive input needed. Just run it, log in in the browser window, and wait.
"""

import os
import sys
import time
import traceback
from pathlib import Path

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_halo_aju2_"

def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")

def main():
    log("Instagram Auto Session Fixer")
    log("=" * 50)
    
    # Delete old stale files
    if SESSION_FILE.exists():
        age = (time.time() - SESSION_FILE.stat().st_mtime) / 3600
        log(f"Old session: {age:.1f}h old — deleting")
        SESSION_FILE.unlink()
    
    if COOKIE_FILE.exists():
        COOKIE_FILE.unlink()
        log("Deleted old cookies.txt")
    
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("❌ Playwright not installed")
        log("Run: venv/Scripts/python -m pip install playwright")
        log("Then: venv/Scripts/python -m playwright install chromium")
        return 1
    
    log("Opening Chrome browser window...")
    log("👉 Log into Instagram now. You have 120 seconds after the page loads.")
    
    cookies = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        page = context.new_page()
        
        # Go to Instagram login
        page.goto("https://www.instagram.com/accounts/login/")
        log("Browser opened. Log in now...")
        
        # Wait 120 seconds for user to log in
        time.sleep(120)
        
        # Extract cookies
        cookies = context.cookies()
        browser.close()
    
    ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
    if not ig_cookies:
        log("❌ No Instagram cookies extracted. Did you log in?")
        return 1
    
    names = {c['name'] for c in ig_cookies}
    log(f"Extracted {len(ig_cookies)} cookies")
    log(f"  sessionid: {'✅' if 'sessionid' in names else '❌'}")
    log(f"  ds_user_id: {'✅' if 'ds_user_id' in names else '❌'}")
    log(f"  csrftoken: {'✅' if 'csrftoken' in names else '❌'}")
    
    if 'sessionid' not in names or 'ds_user_id' not in names:
        log("❌ Missing critical cookies. Login may not have completed.")
        return 1
    
    # Save cookies.txt
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by auto_fix_session.py",
    ]
    for c in ig_cookies:
        domain = c.get("domain", ".instagram.com")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", True) else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
    
    COOKIE_FILE.write_text("\n".join(lines))
    log(f"✅ Saved cookies to {COOKIE_FILE}")
    
    # Save instaloader session
    try:
        import requests
        import instaloader
        
        session = requests.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })
        
        for c in ig_cookies:
            domain = c.get("domain", ".instagram.com")
            session.cookies.set(
                name=c['name'], value=c['value'], domain=domain,
                path=c.get("path", "/"), secure=c.get("secure", True),
                expires=c.get("expires"),
            )
        
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(SESSION_FILE))
        log(f"✅ Saved instaloader session to {SESSION_FILE}")
    except Exception as e:
        log(f"⚠️ Could not save instaloader session: {e}")
    
    # Validate
    log("Validating session...")
    try:
        import requests
        cookies = {}
        for line in COOKIE_FILE.read_text().splitlines():
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split('\t')
            if len(parts) >= 7 and 'instagram' in parts[0].lower():
                cookies[parts[5]] = parts[6]
        
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "X-IG-App-ID": "936619743392459",
            "X-ASBD-ID": "129477",
            "Referer": "https://www.instagram.com/",
        }
        
        session = requests.Session()
        session.headers.update(headers)
        for name, value in cookies.items():
            session.cookies.set(name, value, domain=".instagram.com", path="/")
        
        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30
        )
        
        if resp.status_code == 200:
            data = resp.json()
            user_id = data.get("data", {}).get("user", {}).get("id")
            log(f"✅ Session VALIDATED (user_id: {user_id})")
            log("=" * 50)
            log("DONE! Restart your bot to use the new session.")
            return 0
        else:
            log(f"❌ Validation failed: HTTP {resp.status_code}")
            return 1
    except Exception as e:
        log(f"❌ Validation error: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
