#!/usr/bin/env python3
"""
Auto-refresh Instagram cookies for the Telegram bot.
Run this every 4 hours via cron to keep sessions alive.
Headless — no browser window. Uses browser_cookie3 to pull from Chrome/Edge.
"""

import os
import sys
import time
import traceback
from pathlib import Path

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"

# Detect active Instagram username from cookies to name session file correctly
def get_session_filename(cookies):
    """Find ds_user_id to determine which account these cookies belong to."""
    for c in cookies:
        name = c.name if hasattr(c, 'name') else c.get("name", "")
        if name == "ds_user_id":
            user_id = c.value if hasattr(c, 'value') else c.get("value", "")
            return BASE_DIR / f"session_{user_id}_"
    return BASE_DIR / "session_unknown_"

def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")

def extract_browser_cookies():
    """Extract Instagram cookies from system browser (headless)."""
    try:
        import browser_cookie3
    except ImportError:
        log("browser_cookie3 not installed")
        return None
    
    browsers = [
        ("Chrome", browser_cookie3.chrome),
        ("Edge", browser_cookie3.edge),
        ("Firefox", browser_cookie3.firefox),
    ]
    
    for name, fn in browsers:
        try:
            jar = fn(domain_name="instagram.com")
            cookies = list(jar)
            ig = [c for c in cookies if "instagram" in c.domain]
            
            if not ig:
                continue
            
            names = {c.name for c in ig}
            has_session = 'sessionid' in names
            has_userid = 'ds_user_id' in names
            
            log(f"{name}: {len(ig)} cookies, sessionid={'✅' if has_session else '❌'}, ds_user_id={'✅' if has_userid else '❌'}")
            
            if has_session and has_userid:
                return ig
        except Exception as e:
            log(f"{name} failed: {e}")
            continue
    
    return None

def save_cookies_txt(cookies):
    """Save cookies in Netscape format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by auto_refresh_cookies.py",
    ]
    
    for c in cookies:
        domain = c.domain if hasattr(c, 'domain') else c.get("domain", ".instagram.com")
        flag = "TRUE" if str(domain).startswith(".") else "FALSE"
        path = c.path if hasattr(c, 'path') else c.get("path", "/")
        secure = "TRUE" if getattr(c, 'secure', c.get("secure", True)) else "FALSE"
        expires = getattr(c, 'expires', c.get("expires", 0)) or 0
        name = c.name if hasattr(c, 'name') else c["name"]
        value = c.value if hasattr(c, 'value') else c["value"]
        
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{int(expires)}\t{name}\t{value}")
    
    COOKIE_FILE.write_text("\n".join(lines))
    log(f"Saved {len(cookies)} cookies to cookies.txt")

def save_instaloader_session(cookies):
    """Build requests session and save as instaloader session."""
    try:
        import requests
        import instaloader
        
        session = requests.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })
        
        for c in cookies:
            domain = c.domain if hasattr(c, 'domain') else c.get("domain", ".instagram.com")
            name = c.name if hasattr(c, 'name') else c["name"]
            value = c.value if hasattr(c, 'value') else c["value"]
            path = c.path if hasattr(c, 'path') else c.get("path", "/")
            secure = getattr(c, 'secure', c.get("secure", True))
            expires = getattr(c, 'expires', c.get("expires", None))
            
            session.cookies.set(
                name=name, value=value, domain=domain,
                path=path, secure=secure, expires=expires,
            )
        
        session_file = get_session_filename(cookies)
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(session_file))
        log(f"Saved instaloader session to {session_file.name}")
        return True
    except Exception as e:
        log(f"Failed to save instaloader session: {e}")
        return False

def validate_session():
    """Quick validation via GraphQL user lookup."""
    try:
        import requests
        
        cookies = {}
        for line in COOKIE_FILE.read_text().splitlines():
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split('\t')
            if len(parts) >= 7 and 'instagram' in parts[0].lower():
                cookies[parts[5]] = parts[6]
        
        if 'sessionid' not in cookies:
            return False
        
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "X-IG-App-ID": "936619743392459",
            "X-ASBD-ID": "129477",
            "Referer": "https://www.instagram.com/",
        }
        
        session = requests.Session()
        session.headers.update(headers)
        for name, value in cookies.items():
            session.cookies.set(name, value, domain=".instagram.com", path="/")
        
        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30
        )
        
        if resp.status_code == 200:
            data = resp.json()
            user_id = data.get("data", {}).get("user", {}).get("id")
            if user_id:
                log(f"✅ Session validated (user_id: {user_id})")
                return True
        
        log(f"❌ Validation failed: HTTP {resp.status_code}")
        return False
    except Exception as e:
        log(f"❌ Validation error: {e}")
        return False

def main():
    log("Starting Instagram cookie refresh...")
    
    # Check current cookie freshness
    if COOKIE_FILE.exists():
        age_hours = (time.time() - COOKIE_FILE.stat().st_mtime) / 3600
        cookie_text = COOKIE_FILE.read_text()
        has_sessionid = 'sessionid' in cookie_text
        has_ds_user_id = 'ds_user_id' in cookie_text
        
        log(f"Current cookies.txt: age={age_hours:.1f}h, sessionid={'✅' if has_sessionid else '❌'}, ds_user_id={'✅' if has_ds_user_id else '❌'}")
        
        # If fresh and complete, just validate and exit
        if age_hours <= 4 and has_sessionid and has_ds_user_id:
            if validate_session():
                log("Cookies are fresh and valid. No refresh needed.")
                return 0
            else:
                log("Cookies exist but validation failed. Refreshing...")
        else:
            log("Cookies stale or incomplete. Refreshing...")
    else:
        log("No cookies.txt found. Creating fresh...")
    
    # Extract from browser
    cookies = extract_browser_cookies()
    
    if not cookies:
        log("❌ Could not extract cookies from any browser")
        log("   → Log into Instagram in Chrome/Edge and save the login")
        log("   → Or run fix_session.py for interactive login")
        return 1
    
    # Save
    save_cookies_txt(cookies)
    save_instaloader_session(cookies)
    
    # Validate
    if validate_session():
        log("✅ Cookie refresh complete")
        return 0
    else:
        log("⚠️ Cookies saved but validation failed")
        return 1

if __name__ == "__main__":
    sys.exit(main())
