#!/usr/bin/env python3
r"""
Instagram Cookie Manager
- Tries to refresh cookies headlessly from system browser.
- If that fails or cookies are invalid, opens a visible browser for manual login.
- Saves cookies.txt + instaloader session.
- Validates the session via Instagram GraphQL.

Run manually:
    python cookie_manager.py

Or schedule every 4 hours (Windows Task Scheduler):
    schtasks /create /tn "Instagram Cookie Refresh" /tr "C:\path\to\run_cookie_refresh.bat" /sc hourly /mo 4 /f
"""

import os
import sys
import time
import json
import traceback
from pathlib import Path
from datetime import datetime

# Fix Windows console Unicode output for emoji/log messages
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"

# Map browser_cookie3 extractors by OS
BROWSER_EXTRACTORS = []
try:
    import browser_cookie3
    if sys.platform == "win32":
        BROWSER_EXTRACTORS = [
            ("Chrome", browser_cookie3.chrome),
            ("Edge", browser_cookie3.edge),
            ("Firefox", browser_cookie3.firefox),
        ]
    elif sys.platform == "darwin":
        BROWSER_EXTRACTORS = [
            ("Safari", browser_cookie3.safari),
            ("Chrome", browser_cookie3.chrome),
            ("Firefox", browser_cookie3.firefox),
            ("Edge", browser_cookie3.edge),
        ]
    else:
        BROWSER_EXTRACTORS = [
            ("Chrome", browser_cookie3.chrome),
            ("Firefox", browser_cookie3.firefox),
            ("Edge", browser_cookie3.edge),
        ]
except ImportError:
    pass


def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def get_session_filename(cookies):
    """Find ds_user_id to name the instaloader session file."""
    for c in cookies:
        name = c.name if hasattr(c, "name") else c.get("name", "")
        if name == "ds_user_id":
            user_id = c.value if hasattr(c, "value") else c.get("value", "")
            return BASE_DIR / f"session_{user_id}_"
    return BASE_DIR / "session_unknown_"


def extract_browser_cookies_headless():
    """Extract Instagram cookies from system browser without opening a window."""
    if not BROWSER_EXTRACTORS:
        log("browser_cookie3 not installed")
        return None

    for name, fn in BROWSER_EXTRACTORS:
        try:
            jar = fn(domain_name="instagram.com")
            cookies = list(jar)
            ig = [c for c in cookies if "instagram" in c.domain]

            if not ig:
                continue

            names = {c.name for c in ig}
            has_session = "sessionid" in names
            has_userid = "ds_user_id" in names

            log(f"{name}: {len(ig)} cookies, sessionid={'✅' if has_session else '❌'}, ds_user_id={'✅' if has_userid else '❌'}")

            if has_session and has_userid:
                return ig
        except Exception as e:
            log(f"{name} failed: {e}")
            continue

    return None


def save_cookies_txt(cookies):
    """Save cookies in Netscape format for yt-dlp / gallery-dl / curl_cffi."""
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Auto-generated by cookie_manager.py at {datetime.now().isoformat()}",
    ]

    for c in cookies:
        domain = c.domain if hasattr(c, "domain") else c.get("domain", ".instagram.com")
        flag = "TRUE" if str(domain).startswith(".") else "FALSE"
        path = c.path if hasattr(c, "path") else c.get("path", "/")
        secure = "TRUE" if getattr(c, "secure", c.get("secure", True)) else "FALSE"
        expires = getattr(c, "expires", c.get("expires", 0)) or 0
        name = c.name if hasattr(c, "name") else c["name"]
        value = c.value if hasattr(c, "value") else c["value"]

        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{int(expires)}\t{name}\t{value}")

    COOKIE_FILE.write_text("\n".join(lines))
    log(f"Saved {len(cookies)} cookies to {COOKIE_FILE.name}")


def save_instaloader_session(cookies):
    """Build requests session and save as instaloader session file."""
    try:
        import requests
        import instaloader

        session = requests.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })

        for c in cookies:
            domain = c.domain if hasattr(c, "domain") else c.get("domain", ".instagram.com")
            name = c.name if hasattr(c, "name") else c["name"]
            value = c.value if hasattr(c, "value") else c["value"]
            path = c.path if hasattr(c, "path") else c.get("path", "/")
            secure = getattr(c, "secure", c.get("secure", True))
            expires = getattr(c, "expires", c.get("expires", None))

            session.cookies.set(
                name=name, value=value, domain=domain,
                path=path, secure=secure, expires=expires,
            )

        session_file = get_session_filename(cookies)
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(session_file))
        log(f"Saved instaloader session to {session_file.name}")
        return True
    except Exception as e:
        log(f"Failed to save instaloader session: {e}")
        return False


def validate_session():
    """Validate cookies by hitting Instagram's web_profile_info endpoint."""
    try:
        import requests

        if not COOKIE_FILE.exists():
            return False

        cookies = {}
        for line in COOKIE_FILE.read_text().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            parts = line.split("\t")
            if len(parts) >= 7 and "instagram" in parts[0].lower():
                cookies[parts[5]] = parts[6]

        if "sessionid" not in cookies:
            return False

        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "X-IG-App-ID": "936619743392459",
            "X-ASBD-ID": "129477",
            "Referer": "https://www.instagram.com/",
        }

        session = requests.Session()
        session.headers.update(headers)
        for name, value in cookies.items():
            session.cookies.set(name, value, domain=".instagram.com", path="/")

        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30,
        )

        if resp.status_code == 200:
            data = resp.json()
            user_id = data.get("data", {}).get("user", {}).get("id")
            if user_id:
                log(f"✅ Session validated (user_id: {user_id})")
                return True

        log(f"❌ Validation failed: HTTP {resp.status_code}")
        return False
    except Exception as e:
        log(f"❌ Validation error: {e}")
        return False


def interactive_browser_login():
    """Open a visible browser so the user can log in manually (handles 2FA/challenge)."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        log("Playwright not installed. Run: pip install playwright")
        return None

    log("=" * 60)
    log("Opening visible browser for manual Instagram login")
    log("1. Log into Instagram")
    log("2. Complete any CAPTCHA / 'I'm not a robot' / 2FA")
    log("3. Wait until you see your feed / home page")
    log("4. The script will detect the session automatically")
    log("   (You have up to 30 minutes. Do not close the browser.)")
    log("=" * 60)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        page = context.new_page()
        page.goto("https://www.instagram.com/accounts/login/", wait_until="networkidle")

        max_wait = 1800  # 30 minutes
        start_time = time.time()
        last_log = 0

        while time.time() - start_time < max_wait:
            time.sleep(3)

            # Accept cookies if prompted
            try:
                accept_selectors = [
                    "button:has-text('Allow all cookies')",
                    "button:has-text('Accept')",
                    "button:has-text('Allow essential and optional cookies')",
                    "[role='button']:has-text('Allow all cookies')",
                ]
                for sel in accept_selectors:
                    btn = page.locator(sel).first
                    if btn.is_visible(timeout=1500):
                        btn.click()
                        page.wait_for_timeout(800)
                        break
            except Exception:
                pass

            # Only consider login complete if session cookies exist
            cookies = context.cookies()
            ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
            names = {c.get("name") for c in ig_cookies}
            has_session = "sessionid" in names
            has_userid = "ds_user_id" in names

            if has_session and has_userid:
                log(f"✅ Valid session detected ({len(ig_cookies)} cookies)")
                browser.close()
                return ig_cookies

            # Log progress every 5 seconds
            elapsed = int(time.time() - start_time)
            if elapsed - last_log >= 5:
                last_log = elapsed
                log(f"  Waiting for valid session... ({elapsed}s) — sessionid={'✅' if has_session else '❌'}, ds_user_id={'✅' if has_userid else '❌'}")

        browser.close()
        log("Timeout! Could not detect a valid Instagram session after 30 minutes.")
        log("   Make sure you completed login + CAPTCHA and reached your feed.")
        return None


def main():
    log("=" * 60)
    log("Instagram Cookie Manager")
    log("=" * 60)

    # 1. Check current cookie freshness
    if COOKIE_FILE.exists():
        age_hours = (time.time() - COOKIE_FILE.stat().st_mtime) / 3600
        cookie_text = COOKIE_FILE.read_text(errors="ignore")
        has_sessionid = "sessionid" in cookie_text
        has_ds_user_id = "ds_user_id" in cookie_text
        log(f"Current cookies.txt: age={age_hours:.1f}h, sessionid={'✅' if has_sessionid else '❌'}, ds_user_id={'✅' if has_ds_user_id else '❌'}")

        if age_hours <= 4 and has_sessionid and has_ds_user_id:
            if validate_session():
                log("Cookies are fresh and valid. No refresh needed.")
                return 0
            else:
                log("Cookies exist but validation failed. Refreshing...")
        else:
            log("Cookies stale or incomplete. Refreshing...")
    else:
        log("No cookies.txt found. Creating fresh...")

    # 2. Try headless browser extraction
    cookies = extract_browser_cookies_headless()

    # 3. If headless fails, open visible browser for manual login
    if not cookies:
        log("Headless extraction failed. Falling back to interactive browser login...")
        cookies = interactive_browser_login()

    if not cookies:
        log("❌ Could not obtain cookies")
        return 1

    # 4. Save cookies + session
    save_cookies_txt(cookies)

    names = {c.get("name") for c in cookies}
    if "sessionid" in names and "ds_user_id" in names:
        save_instaloader_session(cookies)
    else:
        log("⚠️ Skipping instaloader session save: sessionid/ds_user_id missing")

    # 5. Validate
    if validate_session():
        log("✅ Cookie refresh complete")
        return 0
    else:
        log("⚠️ Cookies saved but validation failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
