#!/usr/bin/env python3
"""
Manual cookie extractor for 2FA Instagram accounts.
Opens a visible browser, lets you log in + complete 2FA,
then saves cookies for the bot to use.
"""

import json
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    print("Playwright not installed. Run: pip install playwright && python -m playwright install chromium")
    exit(1)

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_manual"

def main():
    print("=" * 60)
    print("Instagram Cookie Extractor (for 2FA accounts)")
    print("=" * 60)
    print()
    print("A browser window will open. Please:")
    print("  1. Log into Instagram")
    print("  2. Complete 2FA if asked")
    print("  3. Wait until you see your feed")
    print("  4. Press ENTER in this terminal to save cookies")
    print()
    input("Press ENTER to open the browser...")
    
    with sync_playwright() as p:
        # Launch visible browser so user can interact
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
        )
        page = context.new_page()
        
        page.goto("https://www.instagram.com/accounts/login/")
        
        print("\nBrowser is open. Log in and complete 2FA.")
        print("Once you see your Instagram feed, come back here and press ENTER.")
        input("\nPress ENTER after you're fully logged in...")
        
        # Extract cookies
        cookies = context.cookies()
        ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
        
        if len(ig_cookies) < 3:
            print("❌ Not enough Instagram cookies found. Are you logged in?")
            browser.close()
            return
        
        print(f"\n✅ Found {len(ig_cookies)} Instagram cookies")
        
        # Save as Netscape cookies.txt for yt-dlp
        lines = ["# Netscape HTTP Cookie File", "# This file was generated by extract_cookies.py"]
        for c in ig_cookies:
            domain = c["domain"]
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", True) else "FALSE"
            expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
            name = c["name"]
            value = c["value"]
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
        
        COOKIE_FILE.write_text("\n".join(lines))
        print(f"🍪 Saved cookies to: {COOKIE_FILE}")
        
        # Also save as JSON for instaloader
        session_data = {
            "cookies": ig_cookies,
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        }
        SESSION_FILE.write_text(json.dumps(session_data, indent=2))
        print(f"📁 Saved session data to: {SESSION_FILE}")
        
        print("\n✅ Done! You can now close the browser and run: python bot.py")
        browser.close()

if __name__ == "__main__":
    main()
