#!/usr/bin/env python3
"""
Instagram Session Fixer v2 — waits for successful login by monitoring URL.
Opens browser, detects when you reach the feed, THEN extracts cookies.
"""

import time
from playwright.sync_api import sync_playwright
from pathlib import Path

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_halo_aju2_"

def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}")

def main():
    log("Instagram Session Fixer v2")
    log("=" * 50)
    
    # Delete old files
    for f in [SESSION_FILE, COOKIE_FILE]:
        if f.exists():
            f.unlink()
            log(f"Deleted old {f.name}")
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        page = context.new_page()
        
        # Go to login page
        page.goto("https://www.instagram.com/accounts/login/")
        log("🌐 Browser opened at Instagram login")
        log("👉 Log in now. I'll wait up to 3 minutes...")
        
        # Wait for URL to change from login page (max 3 minutes)
        logged_in = False
        for i in range(180):  # 180 seconds
            current_url = page.url
            if "instagram.com" in current_url and "login" not in current_url and "challenge" not in current_url:
                logged_in = True
                log(f"✅ Login detected! URL changed to: {current_url[:60]}...")
                break
            
            # Check for challenge/2FA page
            if "challenge" in current_url or "two_factor" in current_url:
                log("⚠️ Instagram is showing a security challenge/2FA. Complete it!")
            
            time.sleep(1)
        
        if not logged_in:
            log("❌ Still on login page after 3 minutes. Login may have failed.")
            browser.close()
            return 1
        
        # Extra wait for cookies to settle
        log("Waiting 5 seconds for cookies to settle...")
        time.sleep(5)
        
        # Extract cookies
        cookies = context.cookies()
        browser.close()
    
    # Filter Instagram cookies
    ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
    names = {c['name'] for c in ig_cookies}
    
    log(f"Extracted {len(ig_cookies)} Instagram cookies")
    for c in ig_cookies:
        log(f"  {c['name']}: {c['value'][:30]}...")
    
    if 'sessionid' not in names:
        log("❌ CRITICAL: No 'sessionid' cookie found!")
        log("   This means Instagram did not create a session.")
        log("   Possible reasons:")
        log("   - Login failed (wrong password)")
        log("   - Account requires 2FA (not completed)")
        log("   - Instagram blocked the login (suspicious activity)")
        log("   - You clicked 'Not Now' on 'Save Login Info'")
        return 1
    
    if 'ds_user_id' not in names:
        log("❌ CRITICAL: No 'ds_user_id' cookie found!")
        return 1
    
    log("✅ All critical cookies present!")
    
    # Save cookies.txt
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by fix_session_v2.py",
    ]
    for c in ig_cookies:
        domain = c.get("domain", ".instagram.com")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", True) else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
    
    COOKIE_FILE.write_text("\n".join(lines))
    log(f"✅ Saved cookies to {COOKIE_FILE}")
    
    # Save instaloader session
    try:
        import requests
        import instaloader
        
        session = requests.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })
        
        for c in ig_cookies:
            domain = c.get("domain", ".instagram.com")
            session.cookies.set(
                name=c['name'], value=c['value'], domain=domain,
                path=c.get("path", "/"), secure=c.get("secure", True),
                expires=c.get("expires"),
            )
        
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(SESSION_FILE))
        log(f"✅ Saved instaloader session to {SESSION_FILE}")
    except Exception as e:
        log(f"⚠️ Could not save instaloader session: {e}")
    
    # Validate
    log("Validating session via GraphQL...")
    try:
        import requests
        cookies = {}
        for line in COOKIE_FILE.read_text().splitlines():
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split('\t')
            if len(parts) >= 7 and 'instagram' in parts[0].lower():
                cookies[parts[5]] = parts[6]
        
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "X-IG-App-ID": "936619743392459",
            "X-ASBD-ID": "129477",
            "Referer": "https://www.instagram.com/",
        }
        
        session = requests.Session()
        session.headers.update(headers)
        for name, value in cookies.items():
            session.cookies.set(name, value, domain=".instagram.com", path="/")
        
        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30
        )
        
        if resp.status_code == 200:
            data = resp.json()
            user_id = data.get("data", {}).get("user", {}).get("id")
            log(f"✅ Session VALIDATED (user_id: {user_id})")
            log("=" * 50)
            log("DONE! Restart your bot to use the new session.")
            return 0
        else:
            log(f"❌ Validation failed: HTTP {resp.status_code}")
            log(f"   Response: {resp.text[:200]}")
            return 1
    except Exception as e:
        log(f"❌ Validation error: {e}")
        return 1

if __name__ == "__main__":
    import sys
    sys.exit(main())
