#!/usr/bin/env python3
"""
Instagram Session Fixer — Interactive Browser Login
Run this to generate fresh cookies.txt and instaloader session.
"""

import os
import sys
import time
import json
import traceback
from pathlib import Path

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_halo_aju2_"

def interactive_login():
    """Open a visible browser, let user log in, extract cookies."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("❌ Playwright not installed. Run: pip install playwright")
        print("   Then: python -m playwright install chromium")
        return False
    
    print("=" * 60)
    print("INTERACTIVE INSTAGRAM LOGIN")
    print("=" * 60)
    print("""
A Chrome browser window will open. Please:
1. Log into Instagram (username + password)
2. If 2FA appears, enter the code
3. Wait until you see your Instagram feed/home
4. Close the browser window or press ENTER here
""")
    input("Press ENTER to open the browser...")
    
    cookies = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        )
        page = context.new_page()
        
        # Go to Instagram
        page.goto("https://www.instagram.com/accounts/login/")
        
        print("\n🌐 Browser is open. Complete the login process.")
        print("   (If you see 'Save login info', click 'Save')")
        input("\nPress ENTER after you're fully logged in and see your feed...")
        
        # Extract cookies
        cookies = context.cookies()
        browser.close()
    
    ig_cookies = [c for c in cookies if "instagram" in c.get("domain", "")]
    if not ig_cookies:
        print("❌ No Instagram cookies extracted")
        return False
    
    names = {c['name'] for c in ig_cookies}
    print(f"\n✅ Extracted {len(ig_cookies)} Instagram cookies")
    print(f"   sessionid: {'✅' if 'sessionid' in names else '❌'}")
    print(f"   ds_user_id: {'✅' if 'ds_user_id' in names else '❌'}")
    print(f"   csrftoken: {'✅' if 'csrftoken' in names else '❌'}")
    
    if 'sessionid' not in names or 'ds_user_id' not in names:
        print("⚠️ Missing critical cookies. Login may not have completed fully.")
        return False
    
    # Save cookies.txt
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by fix_session.py",
    ]
    for c in ig_cookies:
        domain = c.get("domain", ".instagram.com")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", True) else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires") else "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
    
    COOKIE_FILE.write_text("\n".join(lines))
    print(f"✅ Saved cookies to {COOKIE_FILE}")
    
    # Save instaloader session
    try:
        import requests
        import instaloader
        
        session = requests.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        })
        
        for c in ig_cookies:
            domain = c.get("domain", ".instagram.com")
            session.cookies.set(
                name=c['name'],
                value=c['value'],
                domain=domain,
                path=c.get("path", "/"),
                secure=c.get("secure", True),
                expires=c.get("expires"),
            )
        
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(SESSION_FILE))
        print(f"✅ Saved instaloader session to {SESSION_FILE}")
        
    except Exception as e:
        print(f"⚠️ Could not save instaloader session: {e}")
    
    return True

def validate():
    """Test the new session."""
    print("\n" + "=" * 60)
    print("VALIDATING SESSION")
    print("=" * 60)
    
    if not COOKIE_FILE.exists():
        print("❌ No cookies.txt found")
        return False
    
    cookies = {}
    for line in COOKIE_FILE.read_text().splitlines():
        if line.startswith('#') or not line.strip():
            continue
        parts = line.split('\t')
        if len(parts) >= 7 and 'instagram' in parts[0].lower():
            cookies[parts[5]] = parts[6]
    
    if 'sessionid' not in cookies:
        print("❌ No sessionid in cookies")
        return False
    
    import requests
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "X-IG-App-ID": "936619743392459",
        "X-ASBD-ID": "129477",
        "Referer": "https://www.instagram.com/",
    }
    
    session = requests.Session()
    session.headers.update(headers)
    for name, value in cookies.items():
        session.cookies.set(name, value, domain=".instagram.com", path="/")
    
    # Test 1: User lookup
    try:
        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30
        )
        if resp.status_code == 200:
            data = resp.json()
            user = data.get("data", {}).get("user", {})
            print(f"✅ GraphQL user lookup works (ID: {user.get('id', 'N/A')})")
        else:
            print(f"❌ User lookup failed: HTTP {resp.status_code}")
            return False
    except Exception as e:
        print(f"❌ User lookup error: {e}")
        return False
    
    # Test 2: Story fetch (requires auth)
    try:
        from instaloader import Profile
        L = instaloader.Instaloader()
        if SESSION_FILE.exists():
            L.load_session_from_file("halo_aju2", str(SESSION_FILE))
        else:
            L.context._session = session
        
        profile = Profile.from_username(L.context, "instagram")
        print(f"✅ Profile fetch works ({profile.username})")
        
        # Try to get stories (this is the real test)
        # We won't actually download, just check if the API responds
        print("✅ Session appears valid for authenticated content")
        return True
    except Exception as e:
        print(f"⚠️ Profile fetch failed: {e}")
        return False

def main():
    print("\nINSTAGRAM SESSION FIXER")
    print("This will fix your bot's Instagram authentication.\n")
    
    # Delete old stale session
    if SESSION_FILE.exists():
        age_hours = (time.time() - SESSION_FILE.stat().st_mtime) / 3600
        print(f"Old session age: {age_hours:.1f} hours")
        SESSION_FILE.unlink()
        print("Deleted old session file")
    
    if COOKIE_FILE.exists():
        COOKIE_FILE.unlink()
        print("Deleted old cookies.txt")
    
    print()
    
    if interactive_login():
        validate()
        print("\n" + "=" * 60)
        print("DONE! Restart your bot to use the new session.")
        print("=" * 60)
    else:
        print("\n❌ Login failed. Try again.")

if __name__ == "__main__":
    main()
