import os, time, json, tempfile, subprocess, traceback, sys, shutil, sqlite3
from pathlib import Path
import browser_cookie3

BASE_DIR = Path(__file__).parent
COOKIE_FILE = BASE_DIR / "cookies.txt"
SESSION_FILE = BASE_DIR / "session_halo_aju2_"

def log(msg):
    print(msg, flush=True)

def main():
    log("=" * 60)
    log("INSTAGRAM COOKIE REFRESHER (cron mode)")
    log("=" * 60)

    # Step 1: Check if cookies.txt exists and is fresh (< 4 hours)
    if COOKIE_FILE.exists():
        age = time.time() - COOKIE_FILE.stat().st_mtime
        age_hours = age / 3600
        content = COOKIE_FILE.read_text()
        has_sessionid = "sessionid" in content
        has_userid = "ds_user_id" in content
        log(f"cookies.txt exists, age: {age_hours:.2f} hours")
        log(f"has sessionid: {has_sessionid}, has ds_user_id: {has_userid}")
        if age < 4 * 3600 and has_sessionid and has_userid:
            log("Cookies are fresh — validating...")
            try:
                import requests
                cookies = {}
                for line in content.splitlines():
                    if line.startswith("#") or not line.strip():
                        continue
                    parts = line.split("\t")
                    if len(parts) >= 7 and "instagram" in parts[0].lower():
                        cookies[parts[5]] = parts[6]
                headers = {
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                    "X-IG-App-ID": "936619743392459",
                    "Referer": "https://www.instagram.com/",
                }
                session = requests.Session()
                session.headers.update(headers)
                for name, value in cookies.items():
                    session.cookies.set(name, value, domain=".instagram.com", path="/")
                resp = session.get(
                    "https://www.instagram.com/api/v1/users/web_profile_info/",
                    params={"username": "instagram"},
                    timeout=30,
                )
                if resp.status_code == 200:
                    data = resp.json()
                    user = data.get("data", {}).get("user", {})
                    if user and user.get("id"):
                        log(f"Validation passed: fetched user ID {user['id']}")
                        log("RESULT: COOKIES_FRESH")
                        return 0
            except Exception as e:
                log(f"Validation error: {e}")
        log("Cookies are stale or missing key fields — will refresh")
    else:
        log("cookies.txt does not exist")

    # Step 2: Try browser extraction
    log("Step 2: Try browser extraction")
    browsers = [
        ("Chrome", browser_cookie3.chrome),
        ("Edge", browser_cookie3.edge),
        ("Firefox", browser_cookie3.firefox),
    ]
    cookies = None
    for name, fn in browsers:
        try:
            log(f"  Trying {name}...")
            jar = fn(domain_name="instagram.com")
            ig_cookies = [c for c in jar if "instagram" in c.domain]
            names = {c.name for c in ig_cookies}
            has_session = "sessionid" in names
            has_userid = "ds_user_id" in names
            log(f"    Found {len(ig_cookies)} cookies, sessionid={has_session}, ds_user_id={has_userid}")
            if has_session and has_userid:
                log(f"    SUCCESS from {name}")
                cookies = ig_cookies
                break
        except Exception as e:
            log(f"    {name} failed: {e}")

    if not cookies:
        log("  No browser had valid Instagram session cookies")
        log("RESULT: BROWSER_EXTRACTION_FAILED")
        return 1

    # Step 3: Save cookies.txt
    log("Step 3: Save cookies.txt")
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by refresh_cookies_cron.py",
    ]
    for c in cookies:
        domain = c.domain if c.domain else ".instagram.com"
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.path if c.path else "/"
        secure = "TRUE" if getattr(c, "secure", True) else "FALSE"
        expires = str(int(c.expires)) if c.expires else "0"
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c.name}\t{c.value}")
    COOKIE_FILE.write_text("\n".join(lines))
    log(f"  Saved {len(cookies)} cookies to {COOKIE_FILE}")

    # Step 4: Build instaloader session
    log("Step 4: Build instaloader session")
    try:
        import requests as req_lib
        import instaloader
        session = req_lib.Session()
        session.headers.update({
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.instagram.com/",
        })
        for c in cookies:
            domain = c.domain if c.domain else ".instagram.com"
            session.cookies.set(
                name=c.name,
                value=c.value,
                domain=domain,
                path=c.path if c.path else "/",
                secure=getattr(c, "secure", True),
                expires=c.expires,
            )
        L = instaloader.Instaloader()
        L.context._session = session
        L.save_session_to_file(str(SESSION_FILE))
        log(f"  Saved instaloader session to {SESSION_FILE}")
    except Exception as e:
        log(f"  Failed to build instaloader session: {e}")
        traceback.print_exc()

    # Step 5: Validate
    log("Step 5: Validate session")
    try:
        import requests
        content = COOKIE_FILE.read_text()
        cookies = {}
        for line in content.splitlines():
            if line.startswith("#") or not line.strip():
                continue
            parts = line.split("\t")
            if len(parts) >= 7 and "instagram" in parts[0].lower():
                cookies[parts[5]] = parts[6]
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
            "X-IG-App-ID": "936619743392459",
            "Referer": "https://www.instagram.com/",
        }
        session = requests.Session()
        session.headers.update(headers)
        for name, value in cookies.items():
            session.cookies.set(name, value, domain=".instagram.com", path="/")
        resp = session.get(
            "https://www.instagram.com/api/v1/users/web_profile_info/",
            params={"username": "instagram"},
            timeout=30,
        )
        if resp.status_code == 200:
            data = resp.json()
            user = data.get("data", {}).get("user", {})
            if user and user.get("id"):
                log(f"Validation passed: fetched user ID {user['id']}")
                log("RESULT: COOKIES_REFRESHED_SUCCESSFULLY")
                return 0
        log(f"Validation failed: HTTP {resp.status_code}")
        log("RESULT: VALIDATION_FAILED")
        return 1
    except Exception as e:
        log(f"Validation error: {e}")
        log("RESULT: VALIDATION_FAILED")
        return 1

if __name__ == "__main__":
    sys.exit(main())
